### ISSUE TITLE
how can you generate lfw_test_pair.txt

### ISSUE THREAD

**Issue by liquor233** [foamliu/InsightFace-v2#1]
Hi, thank you for your great repo.
I am new in machine learning and I am concerned why should I use a lfw_test_pair.txt and how you generate it? can I just use the whole LFW datasets to test my model?

**Comment by liquor233** [comment]
After reading the code, I understand why you use this txt file, but could you tell me how you generate it or you just downloaded it from somewhere?

**Comment by foamliu** [comment]
Here is the source: http://vis-www.cs.umass.edu/lfw/pairs.txt
