### ISSUE TITLE
lfw accuracy

### ISSUE THREAD

**Issue by mehrdadazizi72** [foamliu/InsightFace-v2#15]
@foamliu Hi, thanks for your great work.
I have run lfw_eval.py with BEST_checkpoint_r101.tar and get these results:

Accuracy: 95.89999999999999%, threshold: 74.7915117227299
Visualizing data/angles.txt...
threshold: 74.7915117227299
mu_0: 84.83895336439484
sigma_0: 5.012717086396831
mu_1: 58.131685076850644
sigma_1: 10.471143670704363
error analysis...
len(fp): 90
len(fn): 156

this results different from your report, what should I do to get the same results?

**Comment by foamliu** [comment]
Have you renamed BEST_checkpoint_r101.tar to BEST_checkpoint.tar before LFW evaluation?

**Comment by mehrdadazizi72** [comment]
i change 'BEST_checkpoint.tar' to 'BEST_checkpoint_r101.tar' in this line:
https://github.com/foamliu/InsightFace-v2/blob/094fb8d0741bc3aceb42e129b8b5ecd2cfc7f37c/lfw_eval.py#L325

**Comment by foamliu** [comment]
Please pull latest code and try again, seems the low accuracy is related with one of my recent experiments.

**Comment by iwanna-sonhs** [comment]
Hello,
I run with your checkpoint https://github.com/foamliu/InsightFace-v2/releases/download/v1.0/BEST_checkpoint_r101.tar.
Accuracy: 99.61666666666666%, threshold: 75.49033778039826

Different with your report, why ?
