### ISSUE TITLE
Megaface crop script leaves only 150K photos out of 1M

### ISSUE THREAD

**Issue by owoshch** [foamliu/InsightFace-v2#19]
Hi!

I'm trying to evaluate my model on Megaface and I've faced the problem.

I have downloaded 1028062 Megaface photos in original resolution.

After running `python3 megaface.py --action crop_megaface` line I have only around 150K aligned photos left. 

I use detector weights provided here: https://github.com/foamliu/InsightFace-v2/issues/17

How did you tackle that problem? How to get 1M of aligned photos?

Thank you :)

**Comment by foamliu** [comment]
As you can see in README, I've 972393 megaface images left. That is almost 1 million.
