### ISSUE TITLE
Training with own dataset

### ISSUE THREAD

**Issue by andang1390** [foamliu/InsightFace-v2#2]
When I change the batch_size from 512 to 32, i have the issues:
RuntimeError: size mismatch, m1: [32 x 73728], m2: [25088 x 512] at /opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/TH/generic/THTensorMath.cpp:940

what should I do?

if i keep batch_size 512, i face issue:
RuntimeError: $ Torch: not enough memory: you tried to allocate 3GB. Buy new RAM! at /opt/conda/conda-bld/pytorch_1549636813070/work/aten/src/TH/THGeneral.cpp:201

However, my mem is 16GB (11GB availabel)

**Comment by foamliu** [comment]
Please have a try:
python3 train.py --end-epoch 50 --lr 0.1 --batch-size 128 --margin-m 0.5 --margin-s 50.0 --network r18
