### ISSUE TITLE
Where can I download ms1m-retinaface-t1.zip?

### ISSUE THREAD

**Issue by Coderx7** [foamliu/InsightFace-v2#22]
Hi, I just wanted to test your code, I downloaded the LFW dataset with the commands you instructed in the readme. and then tried to run `extract.py` which I got the following error for : 
```
PS D:\Codes\arcface_pytorch\impl1\InsightFace-v2> python .\extract.py
Extracting data/ms1m-retinaface-t1.zip...
Traceback (most recent call last):
  File ".\extract.py", line 17, in <module>
    extract('data/ms1m-retinaface-t1.zip')
  File ".\extract.py", line 8, in extract
    zip_ref = zipfile.ZipFile(filename, 'r')
  File "C:\Users\User\Anaconda3\lib\zipfile.py", line 1207, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'data/ms1m-retinaface-t1.zip'
PS D:\Codes\arcface_pytorch\impl1\InsightFace-v2>
```
Can you please elaborate a bit more on this  ? does it need the ms1m? if so which version? aligned? or not? I'd really appreciate it if you can give hint or two regarding the dataset and where to get it. 
Thanks a lot in advance

**Comment by mdhasanai** [comment]
I will find the dataset in https://github.com/deepinsight/insightface/wiki/Dataset-Zoo

**Comment by alicera** [comment]
Do you have the google drive link?
