### ISSUE TITLE
Get accuracy.

### ISSUE THREAD

**Issue by Sotatek-HoangTran** [foamliu/InsightFace-v2#4]
I calculate accuracy by acc = np.mean((output == label).astype(int)) but got an issue.
`Traceback (most recent call last):
  File "train.py", line 203, in <module>
    main()
  File "train.py", line 199, in main
    train_net(args)
  File "train.py", line 113, in train_net
    logger=logger)
  File "train.py", line 182, in train
    acc = np.mean((output == label).astype(int))
RuntimeError: The size of tensor a (1000) must match the size of tensor b (16) at non-singleton dimension 1
`
Can you help me fix this.

**Comment by foamliu** [comment]
Did you encounter this issue during training?

**Comment by foamliu** [comment]
Please feel free to reopen this if it reproduce.
