### ISSUE TITLE
A problem about ROC picture

### ISSUE THREAD

**Issue by xiezheng-cs** [foamliu/InsightFace-v2#6]
Hi, thank you for your great repo.
MegaFace ROC shows the result Verification @ 1e-6 = 0.97781, so it is about resnet50 or resnet100 ??

**Comment by lyhgalaxy** [comment]
How long will it take you?

**Comment by lyhgalaxy** [comment]
Hello，What GPUs do you use and how many?  @xiezheng-cs

**Comment by foamliu** [comment]
@xiezheng-cs ResNet-101, about 10 days on a machine with 2 P-100.
