### ISSUE TITLE
SE-LResNet101E-IR

### ISSUE THREAD

**Issue by MyraBaba** [foamliu/InsightFace-v2#9]
Hi @foamliu ,

where can we get the pretrained model for SE-LResNet101E-IR %99.83 LFW accuracy ?

Best

EDIT:

I found something in model.py .

it is asking **BEST_checkpoint.tar**

where can we download it ?

**Comment by foamliu** [comment]
https://github.com/foamliu/InsightFace-v2/releases/download/v1.0/BEST_checkpoint_r101.tar

**Comment by aais-sonhs** [comment]
Hello,
I run with your checkpoint https://github.com/foamliu/InsightFace-v2/releases/download/v1.0/BEST_checkpoint_r101.tar.
Accuracy: 99.61666666666666%, threshold: 75.49033778039826

Different with your report, why ?

**Comment by Wonder1905** [comment]
I also ran r50 and acc was: Accuracy: 99.55% and not 99.75%
